// languages.mjs
export const languages = {
    en: {
        startGame: "Start Game",
        exitGame: "Exit Game",
        shipPlacementPhase: "Ship Placement Phase",
        firstPlayerReady: "SHIP PLACEMENT\nFirst player, get ready.\nSecond player, look away",
        secondPlayerReady: "SHIP PLACEMENT\nSecond player, get ready.\nFirst player, look away",
        consoleTooSmall: "The console window is too small to run the game.",
        resizeConsole: "Please resize the console window and restart the game.",
        controls: "Controls:",
        arrowKeys: "Arrow keys: Move cursor",
        rotateShip: "R: Rotate ship",
        placeShip: "Enter: Place ship",
        selectLanguage: "Select Language",
        currentResolution: "Current resolution",
        minResolutionRequired: "Minimum required resolution",
    },
    no: {  // Norwegian translations
        startGame: "Start Spill",
        exitGame: "Avslutt Spill",
        shipPlacementPhase: "Fartøyplassering Fase",
        firstPlayerReady: "FARTØYPLASSERING\nFørste spiller, gjør deg klar.\nAndre spiller, se bort",
        secondPlayerReady: "FARTØYPLASSERING\nAndre spiller, gjør deg klar.\nFørste spiller, se bort",
        consoleTooSmall: "Konsollvinduet er for lite til å kjøre spillet.",
        resizeConsole: "Vennligst juster konsollvinduet og start spillet på nytt.",
        controls: "Kontroller:",
        arrowKeys: "Piltaster: Flytt markør",
        rotateShip: "R: Roter fartøy",
        placeShip: "Enter: Plasser fartøy",
        selectLanguage: "Velg Språk",
        currentResolution: "Nåværende oppløsning",
        minResolutionRequired: "Minimumskrav for oppløsning",
    },
};
